import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    {
      href: '/',
      label: 'Home',
    },
    {
      href: '/docs',
      label: 'Docs',
    },
    {
      href: '/todos',
      label: 'Todos',
    },
  ];

  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul className="flex items-center">
              {links.map(({ href, label }) => (
                <li key={href}>
                  <Link href={href}>{label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
